// <auto-generated />
using System;
using GoodHamburguerApp.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburguerApp.Infra.Migrations
{
    [DbContext(typeof(GoodHamburguerContext))]
    partial class GoodHamburguerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburguerApp.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Itens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Sanduiche",
                            CreatedAt = new DateTime(2026, 4, 24, 0, 4, 17, 981, DateTimeKind.Utc).AddTicks(2206),
                            Descricao = "Pão, carne bovina 150g e queijo cheddar.",
                            Nome = "X Burger",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Sanduiche",
                            CreatedAt = new DateTime(2026, 4, 24, 0, 4, 17, 981, DateTimeKind.Utc).AddTicks(2892),
                            Descricao = "Pão, carne bovina 150g, ovo frito e queijo cheddar.",
                            Nome = "X Egg",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Sanduiche",
                            CreatedAt = new DateTime(2026, 4, 24, 0, 4, 17, 981, DateTimeKind.Utc).AddTicks(2893),
                            Descricao = "Pão, carne bovina 150g, bacon e queijo cheddar.",
                            Nome = "X Bacon",
                            Preco = 7.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Batata",
                            CreatedAt = new DateTime(2026, 4, 24, 0, 4, 17, 981, DateTimeKind.Utc).AddTicks(2894),
                            Descricao = "Batata frita crocante.",
                            Nome = "Batata frita",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Refrigerante",
                            CreatedAt = new DateTime(2026, 4, 24, 0, 4, 17, 981, DateTimeKind.Utc).AddTicks(2895),
                            Descricao = "Refrigerante gelado.",
                            Nome = "Refrigerante",
                            Preco = 2.50m
                        });
                });

            modelBuilder.Entity("GoodHamburguerApp.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("ItemPedido", b =>
                {
                    b.Property<int>("ItensId")
                        .HasColumnType("int");

                    b.Property<int>("PedidosId")
                        .HasColumnType("int");

                    b.HasKey("ItensId", "PedidosId");

                    b.HasIndex("PedidosId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("ItemPedido", b =>
                {
                    b.HasOne("GoodHamburguerApp.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodHamburguerApp.Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
